### ISSUE TITLE
[FEATURE] - Label naast radio die disabled is moet ook disabled/grijs zijn

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-radio#55]
**Wat moet er gebeuren**
Er werd reeds opgemerkt dat in de Webuniversum stijl een radio button die disabled is, moeilijk te onderscheiden valt van een actieve.

Ik dacht dat er werd gezegd dat er geen probleem was om in dit geval van de stijl af te wijken. 

Ik weet ook niet of Webuniversum zijn stijl gaat aanpassen of dit moet gebeuren in de webcomponent-vl-ui-radio.

Vandaar dit ticket om een referentie te hebben naar de feature request want in versie 1.0.0 is dit nog niet het geval. 

**Extra info**
Huidige weergave:
![image](https://user-images.githubusercontent.com/29454303/78876553-cc7d7300-7a4f-11ea-8db3-98a0b2126a74.png)

De gewenste weergave zou iets in de stijl van het onderstaande moeten zijn:
![image](https://user-images.githubusercontent.com/29454303/78876839-39910880-7a50-11ea-9eff-6e5a47252e17.png)

**Comment by coemans** [comment]
Ik heb ondertussen overleg gehad met Webuniversum. De huidige kleuren zijn bewust gekozen in kader van toegankelijkheid. Om WCAG (2.1 level AAA) te respecteren, moet het contrast namelijk hoog genoeg zijn.

Het is een moeilijke evenwichtsoefening tussen design en toegankelijkheid. Webuniversum gaat alvast intern terugkoppelen en overleggen met de designers. Vermoedelijk zal er in een nieuwe versie een lichtere kleur toegepast worden. De kleur zal niet zo licht zijn als het voorstel in dit issue, maar hopelijk licht genoeg zodat een disabled variant meer verschil vertoont. Zodra de kleur bekend is, zal deze intern toegepast worden in afwachting van een Webuniversum release en upgrade.
