### ISSUE TITLE
[BUG] - Uitlijnen radio buttons

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-radio#67]
Het is een klein detail, maar ik heb opgemerkt dat op klein scherm de radio buttons ietwat raar worden uitgelijnd. De button staat niet meer in het midden zoals wanneer het scherm groter is. Dit lijkt raar bij het zien van onze lijst met erkenningen.

Volledige weergave lijst op mobile:
![image](https://user-images.githubusercontent.com/29454303/84030988-34d7ca80-a995-11ea-83d3-4d120a83d16a.png)

Detail uitlijning klein venster (of mobile):
![image](https://user-images.githubusercontent.com/29454303/84031035-4620d700-a995-11ea-841e-bae89a9c8538.png)

Detail uitlijning groot venster:
![image](https://user-images.githubusercontent.com/29454303/84031048-4a4cf480-a995-11ea-8f09-c75e7f5ef85d.png)

Graag bevestiging (van Webuniversum?) dat dit de gewenste weergave is of niet.

**Comment by coemans** [comment]
Ik heb nog eens geprobeerd om het probleem te reproduceren, maar ik zie visueel geen verschil in uitlijning tussen desktop en mobile. Ik heb ook kleinere resoluties geprobeerd om het screenshot in het issue te benaderen maar ook daar is geen visueel verschil te zien.

Vermoedelijk is het probleem opgelost. Indien dat niet het geval is, mag het issue opnieuw geopend worden maar kan best een code voorbeeld toegevoegd worden om het probleem te reproduceren.

Desktop:
![screenshot-desktop](https://user-images.githubusercontent.com/11139249/122729651-aa999600-d279-11eb-9ca9-ccb4f7f07d5f.png)

Mobile:
![screenshot-mobile](https://user-images.githubusercontent.com/11139249/122729624-a4a3b500-d279-11eb-8e6b-5e82cea0dba7.png)
