### ISSUE TITLE
[BUG] - Navigeren met pijlen doorheen opties niet mogelijk

### ISSUE THREAD

**Issue by mathiasbosman** [milieuinfo/webcomponent-vl-ui-radio#70]
**Omschrijf het probleem**
Het is in Chrome (Mac & Linux) niet mogelijk om doorheen de opties te navigeren van een radio button group.

Je kan wel naar de eerste optie tabben maar als je dan verder tabt springt de "cursor" naar het volgende form element.
Ook met pijltjes kan je niet in de lijst navigeren.

**Hoe te reproduceren**

- Maak een radio-group aan met meerdere radio buttons
- Tab doorheen het formulier/de pagina tot aan de radio group in Chrome
- Tab opnieuw

(zie [demo](https://webcomponenten.omgeving.vlaanderen.be/demo/vl-radio-group.html))
```html
<vl-radio-group>
  <vl-radio id="radio-1" data-vl-label="Ja" data-vl-value="yes"></vl-radio>
  <vl-radio id="radio-2" data-vl-label="Nee" data-vl-value="no"></vl-radio>
</vl-radio-group>
```

**Gewenst gedrag**
De cursor zou bij het tabben doorheen de opties moeten gaan

**Omgeving:**
 - Browser: Chrome (getest op Linux en Mac)
 - Versie component: 1.0.3

**Comment by coemans** [comment]
In kader van dit issue zijn er 2 bugs die naar boven gekomen zijn:
* Tabben over vl-radio-group elementen is niet mogelijk
* Gebruik van de pijlen binnen een vl-radio-group is niet mogelijk

Dat tabben binnen een groep doorheen de opties niet werkt, is op zich geen bug. Native wordt dit ook niet ondersteund en moeten de pijlen gebruikt worden om binnen een groep te navigeren over de opties.

Ik heb dit issue omgevormd tot de bug i.v.m. het gebruik van de pijlen, voor het ander probleem heb ik #75 aangemaakt.
