### ISSUE TITLE
[BUG] - Radio is niet beschikbaar op de form

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-radio#81]
**Omschrijf het probleem**
Alle standaard form fields (input, select, ...) zijn in js beschikbaar op het form object. Maar voor vl-ui-radio is dit niet het geval.

**Hoe te reproduceren**
html:
```
<form id="search-form">
<input is="vl-input-field" id="trefwoord" type="text" name="trefwoord" />
<vl-radio-group>
<vl-radio id="status-1" name="status" data-vl-label="Status 1" data-vl-value="status1" data-vl-checked />
<vl-radio id="status-2" name="status" data-vl-label="Status 2" data-vl-value="status2" />
</vl-radio-group>
</form>
```

js:
```
form = ... // hier form ref ophalen
form['trefwoord'] // haalt trefwoord input op
form['status'] // zou status radios moeten ophalen, maar dat werkt niet
```

**Gewenst gedrag**
radio buttons zijn beschikbaar op de form, net zoals vl-ui-input (en andere input elementen).

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome / safari
 - Versie component: 1.0.4

**Comment by coemans** [comment]
De huidige code zou voldoende moeten zijn om ook te werken wanneer het name attribuut bij verschillende form elementen identiek is. Ik heb dit geverifieerd bij een medewerker van de HTML SPEC. Vermoedelijk is dit een Chromium bug. Ik heb een bug report toegevoegd. Zodra er feedback is, update ik dit issue.

**Comment by coemans** [comment]
De Chrome bug werd opgelost, maar Firefox en Safari hebben helaas de ElementInternals standaard nog niet geïmplementeerd. Voorlopig onbekend wanneer deze implementatie toegevoegd zal worden. Aangezien we de PR niet onnodig willen laten afwijken van de #master, werd alvast een merge uitgevoerd zonder nadelige effecten in Firefox en Safari. In afwachting kunnen er eenvoudige workarounds toegepast worden.
