### ISSUE TITLE
[BUG] - Een radio programmatisch checken die tot een group behoort unchecked de andere radios in de group niet

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-radio#82]
**Omschrijf het probleem**
Indien meerdere radios in een group zitten dan kan er altijd maar 1 tegelijk geselecteerd zijn. Maar door via js een radio te checken worden er meerdere gechecked.

**Hoe te reproduceren**
html:
```
<form id="search-form">
<input is="vl-input-field" id="trefwoord" type="text" name="trefwoord" />
<vl-radio-group>
<vl-radio id="status-1" name="status" data-vl-label="Status 1" data-vl-value="status1" data-vl-checked />
<vl-radio id="status-2" name="status" data-vl-label="Status 2" data-vl-value="status2" />
</vl-radio-group>
</form>
```

Met deze html is status-1 gechecked. Daarna dit doen checked status-2. Maar status-1 blijft gechecked.

js:
```
radioStatus2 = ... // radio met id "status-2" ophalen
radioStatus2.checked = true;
```

**Screenshots**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/58428396/90115874-fd025000-dd54-11ea-83c0-b5cc2476ddb4.png">

**Gewenst gedrag**
Er mag altijd maar 1 radio in een group checked zijn

**Omgeving (gelieve aan te vullen):**
 - Browser: Chrome
 - Versie component: 1.0.4

**Comment by coemans** [comment]
@FreekRombauts, ik vermoed dat je alleen de vl-ui-radio component geïmporteerd hebt. Kan je eens controleren of je de vl-ui-radio-group component ook importeert? Je kan ook gebruik maken van de all variant zodat er maar één import nodig is.

**Comment by FreekRombauts** [comment]
@coemans , ik heb bij de test gebruik gemaakt van de all variant:

```
import 'vl-ui-radio/dist/vl-radio-all.min.js';
```

**Comment by FreekRombauts** [comment]
@coemans , te snel geweest bij het goedkeuren van deze change. Er is nog een case waarbij het faalt:

```
<vl-radio-group>
<vl-radio name="groep1" data-vl-label="Groep 1 value 1" data-vl-value="g1v1" data-vl-checked />
<vl-radio name="groep1" data-vl-label="groep 1 value 2" data-vl-value="g1v2" />
<vl-radio name="groep2" data-vl-label="Groep 2 value 1" data-vl-value="g2v1" />
<vl-radio name="groep2" data-vl-label="groep 2 value 2" data-vl-value="g2v2" />
</vl-radio-group>
```

* Dit begint met g1v1 checked. 
* Klik op g2v2 of g2v1. Nu is g1v1 niet meer checked. Met andere woorden: het is niet de name property die de groep bepaalt, maar de vl-radio-group. 
* Check nu programmatorisch g1v1. De radio uit groep2 blijft checked, omdat die een andere name property heeft als degene die we hebben gechecked.

Dus er is een discrepantie:
* klikken op radios groepeert per vl-radio-groep
* programmatorische changes groeperen per naam van de vl-radio.

Dat moet consistent zijn.

**Comment by coemans** [comment]
@FreekRombauts ik heb bovenstaande gesimuleerd, maar kan het probleem niet reproduceren:

![#88](https://user-images.githubusercontent.com/11139249/93194336-4248e180-f748-11ea-8ab2-0d100308552e.gif)

**Comment by coemans** [comment]
Blijkbaar werd applicatief nog een oude versie van de branch gebruikt. Het probleem doet zich niet meer voor. Besloten om de name attribuut uitbreiding die op #89 werd voorzien, hier al toe te passen.
