### ISSUE TITLE
[FEATURE] - Getter op een radio en radio group

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-radio#84]
**Wat moet er gebeuren**
Het moet eenvoudig mogelijk zijn om via js code te huidige waarde van een radio button te halen. 

**voorbeeld**
Bijvoorbeeld, gegeven dit soort form:

```
<form id="search-form">
<vl-radio-group>
  <vl-radio id="status-1" name="status" data-vl-label="Status 1" data-vl-value="status1" data-vl-checked />
  <vl-radio id="status-2" name="status" data-vl-label="Status 2" data-vl-value="status2" />
<vl-radio-group>
</form>
```

Moet het in js code mogelijk zijn om de waarde van de gecheckte radio element op te halen. De minimale case zou zijn:
```
// gegeven dat we de checked vl-radio hebben
let checkedRadio = ... // de checked vl-radio ophalen

// dan moet dit kunnen
let checkedValue = checkedRadio.value
```

**bonus features**

Het zou leuk zijn als er direct een aantal convenience features op de radio-group gezet worden, zodat het ophalen van de ene radio in de group die momenteel checked is niet meer nodig is:

Getter:
```
let radioGroup = ... // group ophalen
let checkedValue = radioGroup.value // value uit de group lezen. group gaat die zelf uit het checked element halen
```

Setter:
```
let radioGroup = ... // group ophalen
radioGroup.value = 'status2' // value setten. group gaat zelf het juiste element checken
```

**Comment by coemans** [comment]
De bonus feature heb ik niet geïmplementeerd zoals gevraagd, omdat ook op radio niveau de value setter geen invloed heeft op de checked value. Ik heb wel een getter voor `checkedRadios` toegevoegd, zodat de values van de checked radios eenvoudig opgevraagd kunnen worden. Voldoet dit?

**Comment by FreekRombauts** [comment]
@coemans , getest en werkt.

Ik heb ook geven geexperimenteerd met de `checkRadios` getter, maar die wringt toch wel een beetje. Het probleem zit hem in de list return value.

Momenteel kan je dit doen:

```
<vl-radio-group>
<vl-radio name="groep1" value="groep1-value1" />
<vl-radio name="groep1" value="groep1-value2" />
<vl-radio name="groep2" value="groep2-value1" />
<vl-radio name="groep2" value="groep2-value2" />
</vl-radio-group>
```

in tegenstelling tot `input type="radio"` is het hier niet het name attribuut van de radio dat een groep definieert, maar de radio-group zelf. Er kan altijd maar 1 van de 4 radios tegelijk geselecteerd zijn. Maar indien er altijd maximaal 1 item geselecteerd kan zijn, dan moet `checkedRadios` geen lijst teruggeven, maar een enkel item (of null/undefined want er kan ook geen enkele radio geselecteerd zijn). 

Dat gezegd zijnde, ik ga even PR 88 opnieuw bekijken. Ik heb daar niet geverifieerd dat het blijft werken in dit soort case waar je radios met verschillende name hebt.

**Comment by coemans** [comment]
@FreekRombauts terechte feedback. Het return type is gewijzigd van Array naar HTMLInputElement, de functie werd hernoemd naar `checkedRadio`.
